# Generated by Django 4.0.4 on 2022-04-24 09:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=50)),
                ('author_last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('email_address', models.EmailField(max_length=254)),
                ('credit', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=300)),
                ('revision', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=500)),
                ('author', models.ManyToManyField(to='api_app.author')),
                ('category', models.ManyToManyField(to='api_app.category')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.publication')),
                ('user', models.ManyToManyField(to='api_app.user')),
            ],
        ),
    ]
