# Generated by Django 4.0.4 on 2022-04-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
