# Generated by Django 4.0.4 on 2022-04-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_newuser_note_alter_newuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, to='api_app.books'),
        ),
    ]
