# Generated by Django 4.0.4 on 2022-04-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_remove_newuser_book_books_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
